### ISSUE TITLE
Filtering nested fields

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/voxelgpt#30]
There are a number of issues that arise when filtering on `Label` attributes. Specifically around when to use the notation for nested lists of fields like detections vs when to filter on flat fields like classifications or primitives. 

For example:
* `filter_labels("ground_truth", F("detections.label") == "class")`
* `match(F("eval") == "tp")` for a detections evaluation

**Comment by jacobmarks** [comment]
Closing this as it is no longer relevant :)
