### ISSUE TITLE
Chat history can change the meaning of a query

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/voxelgpt#32]
The chat history can sometimes reword a query to result in a less useful view.

For example, the query `images with a dolphin in them` turned into `show me all images with a label of 'dolphin'`.

On the `coco_gpt_demo` dataset, there are not `dolphin` labels, so the first one would have likely resulted in an interesting `sort_by_similarity` view, but the second query would (and in my opinion should) always result in a filter labels for the class `dolphin`, which would be an empty view. That could be informative if you ask for exactly that query, but adding that level of specificity to the general prompt I gave it initially results in a view that's not very interesting.

**Comment by jacobmarks** [comment]
Closing this as it is no longer relevant :)
