### ISSUE TITLE
Language to query understanding is not always working

### ISSUE THREAD

**Issue by nahidalam** [voxel51/voxelgpt#98]
Hi Voxel51 team. Congratulations on the release.
I just tested  it for a query `show me top 10 most bright images` but it looks like it is doing a query of `view.sort_by(F("brightness").mean(),reverse=True).limit(10)` which is not right.

<img width="1127" alt="Screenshot 2023-06-07 at 11 17 33 AM" src="https://github.com/voxel51/voxelgpt/assets/2341472/9b8ecc12-2202-4219-8b41-fe5f1cf8f582">

Looks like it is related to the [other issue](https://github.com/voxel51/voxelgpt/issues/32) where it is remembering my earlier query `show me top 10 most dark images`

**Comment by jacobmarks** [comment]
Hi @nahidalam , thanks for identifying this, and apologies for the delayed response! VoxelGPT is definitely far from perfect, as is to be expected with an LLM-based (especially GPT-3.5 and before OpenAI function calling was introduced) querying application. I hope it still served as a useful tool for you in your dataset exploration and learning of the FiftyOne query language :)

Seeing as this is stale, I'm going to close the issue for now, but please reach out if you're still interested in improvements like this.
